export const  users = [
  {
    createdAt: "2072-12-27T03:44:22.522Z",
    orgName: "labore-dolor-et",
    tier: 2,
    userName: "Wilburn.Rice",
    status: "active",
    email: "Maverick.Hyatt83@gmail.com",
    phoneNumber: "(553) 208-0727 x31321",
    lastActiveDate: "2099-02-28T23:17:40.013Z",
    profile: {
      firstName: "Darian",
      lastName: "Rolfson",
      phoneNumber: "494-278-0946",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/725.jpg",
      gender: "Male",
      bvn: "815809412",
      address: "Gusikowski Locks",
      currency: "NGN",
      maritalStatus: "Single",
      children: "None",
      typeOfResidence: "Parent's Apartment",
    },
    guarantor: {
      firstName: "Celine",
      lastName: "Monahan",
      phoneNumber: "1-482-227-3654 x71086",
      gender: "Male",
      address: "O'Hara Centers",
      email: "chiki@nini.com",
      relationship: "Sister",
    },
    accountBalance: "496.00",
    accountNumber: "GWQUSEH1",
    bankName: "Polaris Bank",
    uid: "DI33UFD8273",
    socials: {
      facebook: "@lendsqr",
      instagram: "@lendsqr",
      twitter: "@lendsqr",
    },
    education: {
      level: "Bsc",
      employmentStatus: "Employed",
      sector: "FinTech",
      duration: "2 Years",
      officeEmail: "Edna4@yahoo.com",
      monthlyIncome: ["128.57", "118.07"],
      loanRepayment: "122.47",
    },
    id: "1",
  },
  {
    createdAt: "2089-05-21T04:15:40.501Z",
    orgName: "accusamus-minima-repudiandae",
    tier: 3,
    userName: "Jaycee15",
    status: "inactive",
    email: "Veronica_Shanahan93@gmail.com",
    phoneNumber: "(543) 727-0652",
    lastActiveDate: "2039-08-13T13:37:10.433Z",
    profile: {
      firstName: "Mia",
      lastName: "Padberg",
      phoneNumber: "987-749-2057 x6370",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/726.jpg",
      gender: "Male",
      bvn: "374229067",
      address: "Meagan Islands",
      currency: "NGN",
      maritalStatus: "Divorced",
      children: "none",
      typeOfResidence: "Rented Apartment",
    },
    guarantor: {
      firstName: "Johnathon",
      lastName: "Hane",
      phoneNumber: "(573) 413-3844 x9178",
      gender: "Male",
      address: "Goyette Trail",
      email: "john@youngjoe.com",
      relationship: "Brother",
    },
    accountBalance: "800.80",
    accountNumber: "TEJOGWC1007",
    bankName: "Zenith Bank",
    uid: "EFH8348994U",
    socials: {
      facebook: "@lendsqr",
      instagram: "@lendsqr",
      twitter: "@lendsqr",
    },
    education: {
      level: "Bsc",
      employmentStatus: "Employed",
      sector: "FinTech",
      duration: "2 Years",
      officeEmail: "Kitty.Swaniawski28@gmail.com",
      monthlyIncome: ["616.57", "295.72"],
      loanRepayment: "818.12",
    },
    id: "2",
  },
  {
    createdAt: "2021-08-19T01:36:16.155Z",
    orgName: "natus-harum-unde",
    tier: 1,
    userName: "Haylee19",
    status: "blacklisted",
    email: "Mathias_Gottlieb66@gmail.com",
    phoneNumber: "297.557.0046 x7801",
    lastActiveDate: "2097-06-04T13:32:07.211Z",
    profile: {
      firstName: "Alfonso",
      lastName: "Feil",
      phoneNumber: "(844) 555-6996 x4298",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/894.jpg",
      gender: "Male",
      bvn: "640371584",
      address: "Mraz Fields",
      currency: "NGN",
      maritalStatus: "Single",
      children: "None",
      typeOfResidence: "Parent's Apartment",
    },
    guarantor: {
      firstName: "Fiona",
      lastName: "Collier",
      phoneNumber: "769.858.9742 x157",
      gender: "Male",
      address: "Kamron Avenue",
      email: "shrek@fiona.com",
      relationship: "Cousin",
    },
    accountBalance: "419.54",
    accountNumber: "BFIUBZT1146",
    bankName: "GT Bank",
    uid: "23GF37YFGC",
    socials: {
      facebook: "@lendsqr",
      instagram: "@lendsqr",
      twitter: "@lendsqr",
    },
    education: {
      level: "Bsc",
      employmentStatus: "Employed",
      sector: "FinTech",
      duration: "2 Years",
      officeEmail: "Jessyca_Franey@yahoo.com",
      monthlyIncome: ["417.01", "128.60"],
      loanRepayment: "326.72",
    },
    id: "3",
  },
  {
    createdAt: "2077-07-01T16:25:36.402Z",
    orgName: "aliquam-velit-ab",
    tier: 2,
    userName: "Allan.Bechtelar72",
    email: "Mckenzie87@gmail.com",
    status: "active",
    phoneNumber: "1-592-749-9116 x98760",
    lastActiveDate: "2009-04-20T20:23:09.964Z",
    profile: {
      firstName: "Nolan",
      lastName: "Berge",
      phoneNumber: "438.702.2279 x5984",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/774.jpg",
      gender: "Male",
      bvn: "368681174",
      address: "Asha Isle",
      currency: "NGN",
      maritalStatus: "Married",
      children: "2",
      typeOfResidence: "Parent's Apartment",
    },
    guarantor: {
      firstName: "Vergie",
      lastName: "Metz",
      phoneNumber: "658.307.7471",
      gender: "Male",
      address: "Rolfson Forge",
      email: "john@youngjoe.com",
      relationship: "Brother",
    },
    accountBalance: "510.90",
    accountNumber: "EXOAVND1",
    bankName: "Polaris Bank",
    uid: "EWVG8WF8FW4",
    socials: {
      facebook: "@lendsqr",
      instagram: "@lendsqr",
      twitter: "@lendsqr",
    },
    education: {
      level: "Bsc",
      employmentStatus: "Employed",
      sector: "FinTech",
      duration: "2 Years",
      officeEmail: "Katlynn.Ortiz@hotmail.com",
      monthlyIncome: ["618.34", "169.47"],
      loanRepayment: "707.96",
    },
    id: "4",
  },
  {
    createdAt: "1993-11-09T12:12:00.532Z",
    orgName: "quas-et-ut",
    tier: 2,
    userName: "Ezequiel_Harber",
    status: "active",
    email: "Mckenna_Muller31@hotmail.com",
    phoneNumber: "1-992-532-3120 x38790",
    lastActiveDate: "2096-12-17T21:24:42.496Z",
    profile: {
      firstName: "Faye",
      lastName: "Ward",
      phoneNumber: "235.928.4206 x4446",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/394.jpg",
      gender: "Male",
      bvn: "657515469",
      address: "Larson Inlet",
      currency: "NGN",
      maritalStatus: "Single",
      children: "none",
      typeOfResidence: "Parent's Apartment",
    },
    guarantor: {
      firstName: "Barrett",
      lastName: "Kirlin",
      phoneNumber: "347.684.8866 x28414",
      gender: "Male",
      address: "Amari Ramp",
      email: "john@youngjoe.com",
      relationship: "Brother",
    },
    accountBalance: "646.80",
    accountNumber: "AZCOBAQ1",
    bankName: "Polaris Bank",
    uid: "H72GF78GC23487",
    socials: {
      facebook: "@lendsqr",
      instagram: "@lendsqr",
      twitter: "@lendsqr",
    },
    education: {
      level: "Bsc",
      employmentStatus: "Employed",
      sector: "FinTech",
      duration: "2 Years",
      officeEmail: "Kurtis24@hotmail.com",
      monthlyIncome: ["859.80", "526.10"],
      loanRepayment: "67.82",
    },
    id: "5",
  },
  {
    createdAt: "2000-03-28T10:49:25.631Z",
    orgName: "accusantium-voluptatem-voluptate",
    tier: 3,
    userName: "Brady.Bauch34",
    status: "pending",
    email: "Brandyn_McCullough@yahoo.com",
    phoneNumber: "489.712.9802 x562",
    lastActiveDate: "2080-12-27T13:57:48.039Z",
    profile: {
      firstName: "Raymond",
      lastName: "Prosacco",
      phoneNumber: "997.248.4393 x091",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/66.jpg",
      gender: "Male",
      bvn: "271546694",
      address: "Colt Lock",
      currency: "NGN",
      maritalStatus: "Married",
      children: "3",
      typeOfResidence: "Own Building",
    },
    guarantor: {
      firstName: "Ben",
      lastName: "Homenick",
      phoneNumber: "(215) 438-1017 x8240",
      gender: "Male",
      address: "Nicolette Park",
      email: "tisk@tisk.com",
      relationship: "Cousin",
    },
    accountBalance: "501.40",
    accountNumber: "HYAELVP1",
    bankName: "Access Bank",
    uid: "3FH82F4HFHF",
    socials: {
      facebook: "@lendsqr",
      instagram: "@lendsqr",
      twitter: "@lendsqr",
    },
    education: {
      level: "Bsc",
      employmentStatus: "Employed",
      sector: "FinTech",
      duration: "2 Years",
      officeEmail: "Rashawn_Douglas35@gmail.com",
      monthlyIncome: ["502.11", "646.45"],
      loanRepayment: "137.91",
    },
    id: "6",
  },
  {
    createdAt: "2072-05-09T06:05:41.271Z",
    orgName: "sint-ipsa-voluptatem",
    tier: 2,
    userName: "Gino.Boyle50",
    status: "pending",
    email: "Cristian_Schmeler70@yahoo.com",
    phoneNumber: "(803) 392-7754 x43071",
    lastActiveDate: "2045-01-30T16:39:19.040Z",
    profile: {
      firstName: "Marques",
      lastName: "Zboncak",
      phoneNumber: "683.205.1779 x568",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1090.jpg",
      gender: "Male",
      bvn: "740474064",
      address: "Johns Fort",
      currency: "NGN",
      maritalStatus: "Single",
      children: "none",
      typeOfResidence: "Parent's Apartment",
    },
    guarantor: {
      firstName: "Dillon",
      lastName: "Pfeffer",
      phoneNumber: "1-686-985-6165",
      gender: "Male",
      address: "Hector Camp",
      email: "john@youngjoe.com",
      relationship: "Brother",
    },
    accountBalance: "347.43",
    accountNumber: "SNFUVUX1",
    bankName: "Polaris Bank",
    uid: "F72G4FUESIC",
    socials: {
      facebook: "@lendsqr",
      instagram: "@lendsqr",
      twitter: "@lendsqr",
    },
    education: {
      level: "Bsc",
      employmentStatus: "Employed",
      sector: "FinTech",
      duration: "2 Years",
      officeEmail: "Aiyana18@hotmail.com",
      monthlyIncome: ["613.08", "159.26"],
      loanRepayment: "941.59",
    },
    id: "7",
  },
];

